### ISSUE TITLE
Nu merge

### ISSUE THREAD

**Issue by catalintira** [macocianradu/Cardposting#1]
Buna seara nu merge aplicatia. Pret? O zi buna!
![mac](https://user-images.githubusercontent.com/33908857/105400523-b8e17880-5c2d-11eb-86c3-21cbf9fd9948.png)

**Comment by macocianradu** [comment]
UAU COAIEMIU

**Comment by macocianradu** [comment]
weird ca n-am primit notificare, da am stiut direct unde sa ma uit :))
